set -g mouse on
set -g history-limit 200000
set -g base-index 1
setw -g pane-base-index 1

unbind C-b
set -g prefix C-o
bind C-o send-prefix

bind r source-file ~/.tmux.conf \; display-message "tmux reloaded"
bind | split-window -h
bind - split-window -v

# shared history and session state
set -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
bind-key S command-prompt -p "new-session:" "new-session -s %% -d"

set -g status-bg colour235
set -g status-fg white
set -g status-left-length 40
set -g status-right-length 100
